server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:}

spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      keepaliveTime: 300000   # 5 min
      idle-timeout: 600000    # 10 min
  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE:always}

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        vertex-ai: false
        chat:
          options:
            model: gemini-2.5-flash
        embedding:
          api-key: ${GEMINI_API_KEY}
          vertex-ai: false

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: false
    properties:
      hibernate.format_sql: true
